import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Image from 'next/image';
// import styles from '../styles/Home.module.css'

export default function Home() {

  useEffect(() => {
    console.log("testing loading behaivour");
  });


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>test</h1>
      </main>
    </div>
  );
}
